### ISSUE TITLE
Running unpacked

### ISSUE THREAD

**Issue by inverse** [nambrot/erutpa#20]
Saw your post regarding getting requireJs working with the yo chrome-extension generator. 

Are you able to run this extension unpacked or do you have to perform a full release and execute that?

**Comment by nambrot** [comment]
I got it to run unpacked, whats the issue you are running into?

**Comment by inverse** [comment]
Ahh I think I was just overlooking things. Whoops :/ It compiles the coffee in directory and I was expecting some kinda unpacked folder :/ My bad! thanks for sharing the code!

**Comment by tmilar** [comment]
Hey, I have been also trying to unpack for testing your app (liked your work on requireJs + chrome extension), but I couldn't get it done. 

When I grunt it manages to complete without errors, except the following one: 

Running "uglify:dist\scripts\contentscript.js" (uglify) task

> > Destination (dist\scripts\contentscript.js) not written because src files were empty.

When I try to load unpacked in chrome, I get the error:

![screenshot 2015-06-18 17 28 21](https://cloud.githubusercontent.com/assets/3988039/8241484/fae20f46-15df-11e5-883b-485e55cabb2d.png)

The directory ends up looking like this:

![screenshot 2015-06-18 17 25 33](https://cloud.githubusercontent.com/assets/3988039/8241452/cd27818a-15df-11e5-9f35-d225501c7211.png)

Btw I'm on Windows 8.1

Would really appreciate some help.

**Comment by nambrot** [comment]
It looks like grunt did not compile the coffeescript to javascript. I'm not sure how it works on windows, but you want to make sure what the coffeescript compilers runs correctly on Windows.
